class Product{
  final int id;
  final String name;
  final String category;
  final String image;
  final String description;
  int  price;
  int quantity;
  final String Start;
  Product({
    required this.name,
    required this.quantity,
    required this.price,
    required this.image,
    required this.description,
    required this.category,
    required this.id,
    required this.Start
  });

}
class MyProducts {
  static List<Product> allProducts = [
    Product(
        Start: 'Star:',
        name: ' (लकड़ी) Work',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/Carpanter.jpeg",
        description: "Perform basic care and maintenance, including changing oil, checking fluid levels, and rotating tires. Repair or replace worn parts, such as brake pads, wheel bearings, and sensors",
        category: "Trending Now",
        id: 1),
    Product(
        Start: "Star: ",
        name: 'Mechanic',
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic1.jpg",
        description: "Perform basic care and maintenance, including changing oil, checking fluid levels, and rotating tires. Repair or replace worn parts, such as brake pads, wheel bearings, and sensors",
        category: "Out-off Stock",
        id: 1),
    Product(Start: "Star: ",
        name: 'लकड़ी (wala)',
        quantity: 1, price: 80,
        image: "Assets/Carpenter/carpenter4.jpg",
        description: "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Helo Paint',
        quantity: 1, price: 130,
        image: "Assets/Painter/paint4.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Hired",
        id: 1),
    Product(Start: "Star: ",
        name: 'Painting Mechine',
        quantity: 1, price: 130,
        image: "Assets/Painter/paint1.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Helo Mechanic',
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic1.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Paint',
        quantity: 1, price: 130,
        image: "Assets/Painter/paint4.jpg",
        description: "Let's paint the world,Bhiwani,Haryana (India) \n let's chat with us..",
        category: "Trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Carpenter',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/Carpanter.jpeg",
        description: "Perform basic care and maintenance, including changing oil, checking fluid levels, and rotating tires. Repair or replace worn parts, such as brake pads, wheel bearings, and sensors",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: '',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/Carpanter.jpeg",
        description: "Perform basic care and maintenance, including changing oil, checking fluid levels, and rotating tires. Repair or replace worn parts, such as brake pads, wheel bearings, and sensors",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Pooma Air Ma',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/Carpanter.jpeg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Pooma Air Ma',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/Carpanter.jpeg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Pooma Air Ma',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/Carpanter.jpeg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Lakdi work',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/Carpanter.jpeg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Carpenter',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/carpenter4.jpg",
        description: "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Carpenter',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/carpenter3.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Carpenter Shop',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/carpenter2.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Mechanic',
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic1.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Carpenter',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/carpenter4.jpg",
        description: "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Carpenter',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/carpenter3.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Carpenter Shop',
        quantity: 1, price: 130,
        image: "Assets/Carpenter/carpenter2.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Trending Now",
        id: 1),
    Product(Start: 'Star: ""',
        name: 'Mechanic',
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic1.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Trending Now",
        id: 1),
  ];
  static List<Product> Mechanic = [
    Product(
        Start: 'Star:',
        name: 'Mechanic',
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic1.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(
        Start: "Star: ",
        name: 'Mechanic',
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic2.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(
        Start: "Star: ",
        name: 'Mechanic',
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic3.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: "Mechanic",
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic4.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Mechanic',
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic5.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Mechanic',
        quantity: 1, price: 130,
        image: "Assets/Mechanic/mechanic6.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
  ];
  static List<Product> Painter = [
    Product(Start: "Star: ",
        name: 'Helo Paint',
        quantity: 1, price: 130,
        image: "Assets/Painter/paint1.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Hired",
        id: 1),
    Product(Start: "Star: ",
        name: 'Painting Mechine',
        quantity: 1, price: 130,
        image: "Assets/Painter/paint2.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Helo Paint',
        quantity: 1, price: 130,
        image: "Assets/Painter/paint6.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Hired",
        id: 1),
    Product(Start: "Star: ",
        name: 'Painting Mechine',
        quantity: 1, price: 130,
        image: "Assets/Painter/paint5.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Helo Paint',
        quantity: 1, price: 130,
        image: "Assets/Painter/paint4.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Hired",
        id: 1),
    Product(Start: "Star: ",
        name: 'Painting Mechine',
        quantity: 1, price: 130,
        image: "Assets/Painter/paint3.jpg",
        description:  "We can Develop Your Furniture, in a limited time and our service will be satisfied you. \n let's chat...",
        category: "Trending Now",
        id: 1),
  ];
  static List<Product> Carpenter = [
    Product(
        Start: 'Star:',
        name: 'Nike Air Max 200',
        quantity: 1, price: 130,
        image: "Assets/Images/mechanic5.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(
        Start: "Star: ",
        name: 'Nike Air Max 200',
        quantity: 1, price: 130,
        image: "Assets/Images/mechanic5.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(
        Start: "Star: ",
        name: 'Nike Air Max 209',
        quantity: 1, price: 130,
        image: "Assets/Images/mechanic5.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Nike Air Max 200',
        quantity: 1, price: 130,
        image: "Assets/Images/mechanic5.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Ni Air Max 200',
        quantity: 1, price: 130,
        image: "Assets/Images/mechanic5.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
    Product(Start: "Star: ",
        name: 'Ni Air Max 200',
        quantity: 1, price: 130,
        image: "Assets/Images/mechanic5.jpg",
        description: "Helo world this is sunny rohiwal from haryana india,earth",
        category: "trending Now",
        id: 1),
  ];
}